causes_of_homelessness = {1:  "Asked to move out",
                          2:  "Dangerous living situation",
                          3:  "Divorce/separation",
                          4:  "Domestic violence",
                          5:  "Family conflict",
                          6:  "Fire/other disaster",
                          7:  "Illegal eviction",
                          8:  "Illness/medical expenses",
                          9:  "Incarceration",
                          10: "Leaving fostercare",
                          11: "Legal eviction",
                          12: "Loss of Benefits",
                          13: "Loss of work",
                          14: "Mental illness",
                          15: "Not receiving medical care",
                          16: "Public housing closed",
                          17: "Relocation",
                          18: "Rent increase",
                          19: "Substance abuse",
                          20: "Foreclosure related"}
